### ISSUE TITLE
Loading Screens

### ISSUE THREAD

**Issue by MidnightFlamingo97** [The-Cocktail-Cache-Team/cocktail-cache#1]
Create a new feature where the main content of a page is "display:none;" and a full screen loading page with animated loading circle is loaded instead (see figma mock for loading screen)

Once the getAllCocktails promise has populated the allDrinks array, make the loading screen stop displaying and display the page content instead.

This feature will improve user experience, showing them content is loading - rather than seeing a screen with no data loaded

**Comment by thecowsays** [comment]
QA this by for UX:

Does it load within less than 4 seconds? If longer, try to find a way to decrease loading time. Studies show that users will exit a page if it takes longer than 3 seconds to load.

**Comment by MidnightFlamingo97** [comment]
Loading screen stuff added and pulled into core-features
