### ISSUE TITLE
Update Nav Menus & Header

### ISSUE THREAD

**Issue by thecowsays** [The-Cocktail-Cache-Team/cocktail-cache#29]
We need to update _every_ page to have the same menu items:

[ Item - Link ]

- Brand, Logo - index.html
- Browse - browse.html
- Quiz - quiz.html
- Random - random.html
- About - about.html
- Search Icon - [search function]

**Comment by MidnightFlamingo97** [comment]
@thecowsays I think this is a non-issue as my latest pull request does this
